[package]
name = "taskmgr"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
tokio-util = "0.7.18"
